CREATE TABLE IF NOT EXISTS Users
(
    User_ID SERIAL PRIMARY KEY NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    isAdmin BOOLEAN NOT NULL,
    Username TEXT UNIQUE NOT NULL,
    Password TEXT NOT NULL
)