CREATE TABLE IF NOT EXISTS Sessions
(
    User_ID INTEGER NOT NULL,
    Token TEXT PRIMARY KEY NOT NULL,
    Expiry INTEGER NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID)
        ON DELETE CASCADE
)