CREATE TABLE IF NOT EXISTS Submissions
(
    Submission_ID SERIAL PRIMARY KEY NOT NULL,
    Source TEXT UNIQUE NOT NULL,
    Fact TEXT UNIQUE NOT NULL,
    Co2 REAL NOT NULL,
    Timespan INTEGER NOT NULL
)